name: Create Flatpak PR
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Auto Merge PR
      env:
        PUSH_TOKEN: ${{ secrets.MERGE_TOKEN }}
      run: |
        echo $PUSH_TOKEN >> auth.txt
        gh auth login --with-token < auth.txt
        rm auth.txt
        gh pr merge https://github.com/FreeTubeApp/FreeTube/pull/${{ github.event.pull_request.number }} --auto
